trigger: none

schedules:
- cron: "0 5 * * *"
  displayName: Mon through Sun at 9:00 PM (UTC-8:00)
  branches:
    include:
    - main
  always: true

jobs:

- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/coreclr/templates/build-job.yml
    buildConfig: checked
    platforms:
    - windows_x86
    - windows_x64
    jobParameters:
      testGroup: outerloop

- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/coreclr/templates/build-job.yml
    buildConfig: Release
    platforms:
    - windows_x86
    - windows_x64
    jobParameters:
      testGroup: outerloop

- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/libraries/build-job.yml
    buildConfig: Release
    platforms:
    - windows_x86
    - windows_x64
    jobParameters:
      isOfficialBuild: false
      liveRuntimeBuildConfig: Release

- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/common/templates/runtimes/build-test-job.yml
    buildConfig: checked
    platforms:
    - CoreClrTestBuildHost # Either OSX_x64 or Linux_x64
    jobParameters:
      testGroup: outerloop

# Test most platforms in composite mode as the expected mainline shipping mode
- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/common/templates/runtimes/run-test-job.yml
    helixQueuesTemplate: /eng/pipelines/coreclr/templates/helix-queues-setup.yml
    buildConfig: checked
    platforms:
    - windows_x64
    - windows_x86
    jobParameters:
      testGroup: outerloop
      readyToRun: true
      compositeBuildMode: true
      displayNameArgs: R2R_Composite
      liveLibrariesBuildConfig: Release

# Outerloop testing in non-composite mode
- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/common/templates/runtimes/run-test-job.yml
    helixQueuesTemplate: /eng/pipelines/coreclr/templates/helix-queues-setup.yml
    buildConfig: checked
    platforms:
    - windows_x64
    - windows_x86
    jobParameters:
      testGroup: outerloop
      readyToRun: true
      displayNameArgs: R2R
      liveLibrariesBuildConfig: Release
